apiVersion: v1
kind: Service
metadata:
  name: aspire-endo-frontend
  namespace: aspire-endo
  labels:
    app: aspire-endo-frontend
    app.kubernetes.io/part-of: aspire-endoexpertise
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: aspire-endo-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
